Create `ru_ru.json`
FiniteReality/embeddium pull request #275
Opened 2024-05-01 18:27 UTC by mpustovoi

Both `Sodium` and `Embeddium` lang folders

2024-05-01 18:34 UTC, mpustovoi commented
I have read, and hereby affirm the entire contents of the Developer Certificate of Origin.

2024-05-01 18:51 UTC, embeddedt requested changes
The strings in the `sodium/lang` file need to mention Embeddium (even though the key is still sodium), **except** for `sodium.options.buttons.donate`. That one should be left as-is.

2024-05-08 01:56 UTC, embeddedt approved these changes
This looks good. We are still sorting out how we want to handle the logistics of translations going forward, hence the delay in merging.

2025-08-01 01:40 UTC, rikzun commented
BRUH

2026-05-14 11:43 UTC, closed without merging